version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # We need to decide on when we upgrade Sphinx manually,
      # as historically, this has been proven to often imply larger changes
      # (RTD compat, upgrading extensions, other dependencies, our content, etc.).
      - dependency-name: "sphinx"
